AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
  - 'bin/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'spec/**/*'
  - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: true
  EnforcedStyle: final_newline

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/MethodLength:
  CountComments: false
  Max: 55

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false